CREATE TABLE IF NOT EXISTS `#__home_` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,

`asset_id` INT(10) UNSIGNED NOT NULL DEFAULT '0',

`ordering` INT(11)  NOT NULL ,
`state` TINYINT(1)  NOT NULL ,
`checked_out` INT(11)  NOT NULL ,
`checked_out_time` DATETIME NOT NULL ,
`created_by` INT(11)  NOT NULL ,
`modified_by` INT(11)  NOT NULL ,
`name` VARCHAR(255)  NOT NULL ,
`discover_title` VARCHAR(255)  NOT NULL ,
`discover_text` TEXT NOT NULL ,
`discover_main_title` VARCHAR(255)  NOT NULL ,
`discover_main_image` VARCHAR(255)  NOT NULL ,
`discover_main_link` VARCHAR(255)  NOT NULL ,
`discover_first_title` VARCHAR(255)  NOT NULL ,
`discover_first_image` VARCHAR(255)  NOT NULL ,
`discover_first_link` VARCHAR(255)  NOT NULL ,
`discover_second_title` VARCHAR(255)  NOT NULL ,
`discover_second_image` VARCHAR(255)  NOT NULL ,
`discover_second_link` VARCHAR(255)  NOT NULL ,
`discover_third_title` VARCHAR(255)  NOT NULL ,
`discover_third_image` VARCHAR(255)  NOT NULL ,
`discover_third_link` VARCHAR(255)  NOT NULL ,
`careers_title` VARCHAR(255)  NOT NULL ,
`careers_text` TEXT NOT NULL ,
`companies_title` VARCHAR(255)  NOT NULL ,
`companies_text` TEXT NOT NULL ,
`community_title` VARCHAR(255)  NOT NULL ,
`community_text` TEXT NOT NULL ,
`community_first_title` VARCHAR(255)  NOT NULL ,
`community_first_image` VARCHAR(255)  NOT NULL ,
`companies_first_text` TEXT NOT NULL ,
`community_second_title` VARCHAR(255)  NOT NULL ,
`community_second_image` VARCHAR(255)  NOT NULL ,
`companies_second_text` TEXT NOT NULL ,
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8mb4_unicode_ci;

